# Generated by Django 5.0.4 on 2025-01-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usersignup_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactFullName', models.CharField(max_length=50)),
                ('contactEmail', models.CharField(max_length=50)),
                ('contactPhoneNumber', models.CharField(max_length=15)),
                ('contactSubject', models.CharField(max_length=50)),
                ('contactMessage', models.TextField()),
            ],
        ),
    ]
