# Generated by Django 5.0.4 on 2025-02-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pickuprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickuprequest',
            old_name='timestamp',
            new_name='requested_at',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
