# Generated by Django 5.0.4 on 2025-02-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_timestamp_pickuprequest_requested_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickuprequest',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='contact',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='quantity',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
