# Generated by Django 5.0.4 on 2025-03-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_recycler_alter_pickuprequest_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigned_recycler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=10)),
                ('address', models.CharField(default='Unknown', max_length=255)),
                ('quantity', models.CharField(default='Unknown', max_length=50)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
    ]
