# Generated by Django 5.0.4 on 2025-03-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_assigned_recycler'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycler',
            name='set_password',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
