# Generated by Django 5.0.4 on 2025-03-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_recycler_set_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycler',
            name='set_password',
            field=models.CharField(max_length=100),
        ),
    ]
