# Generated by Django 5.0.4 on 2025-03-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_recycler_set_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recycler',
            old_name='set_password',
            new_name='password',
        ),
    ]
