# Generated by Django 5.0.4 on 2025-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_recyclercreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclercreate',
            name='assigned_area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recyclercreate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recyclercreate',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='recyclercreate',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10),
        ),
    ]
