# Generated by Django 5.0.4 on 2025-03-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_recyclercreate_assigned_area_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recycler',
        ),
        migrations.AlterField(
            model_name='recyclercreate',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
