# Generated by Django 5.0.4 on 2025-03-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_recycler_alter_recyclercreate_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='total_pickup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='total_recycled',
            field=models.IntegerField(default=0),
        ),
    ]
