# Generated by Django 5.0.4 on 2025-03-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_usersignup_total_pickup_usersignup_total_recycled'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
