# Generated by Django 5.0.4 on 2025-03-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_usersignup_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclercreate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
