# Generated by Django 5.0.4 on 2025-03-27 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_pickuprequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuprequest',
            name='user',
        ),
    ]
