# Generated by Django 5.0.4 on 2025-03-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_usersignup_options_alter_usersignup_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersignup',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usersignup',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='usersignup',
            name='full_name',
            field=models.CharField(default='Sha', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
