# Generated by Django 5.0.4 on 2025-03-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_usersignup_options_alter_usersignup_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
