# Generated by Django 5.0.4 on 2025-03-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_pickuprequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
