# Generated by Django 5.0.4 on 2025-03-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_pickuprequest_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='center_name',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='usersignup',
            name='location',
        ),
        migrations.AddField(
            model_name='usersignup',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='total_recycled',
            field=models.FloatField(default=0.0),
        ),
    ]
