# Generated by Django 5.0.4 on 2025-03-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_usersignup_center_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
