# Generated by Django 5.0.4 on 2025-03-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_usersignup_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='is_staff',
        ),
    ]
