# Generated by Django 5.0.4 on 2025-03-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_usersignup_is_active_usersignup_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='user',
            field=models.IntegerField(),
        ),
    ]
