# Generated by Django 5.0.4 on 2025-03-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_pickuprequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
