# Generated by Django 5.0.4 on 2025-03-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_pickuprequest_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_recycler',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='total_recycled',
            field=models.IntegerField(default=0),
        ),
    ]
