# Generated by Django 5.0.4 on 2025-03-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_assigned_recycler_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
